[train_2_2_chemistry]
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn.final.torch
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn.final.torch.pickle
save_pos=paper_v1/results/semi_train_2_2_chemistry.npz
score_ap_json=paper_v1/results/semi_2_2_score_precision.json
score_ap_table=paper_v1/results/semi_2_2_score_precision.tsv

[train_3_2_chemistry]
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=0
train_sample_fraction=1.0
val_sample=0
val_sample_fraction=1.0
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=10
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00243.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00243_mrv_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00243.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00243_mrv_val.npz
best_supervised_model_name=paper_v1/models/m6A_3_2_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_3_2_supervised_cnn.final.torch.pickle
pretrain_model_name=paper_v1/models/m6A_3_2_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_3_2_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_3_2_semi_supervised_cnn.final.torch.pickle
save_pos=paper_v1/results/semi_train_3_2_chemistry.npz
score_ap_json=paper_v1/results/semi_3_2_score_precision.json
score_ap_table=paper_v1/results/semi_3_2_score_precision.tsv

[train_revio_chemistry]
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=0
train_sample_fraction=1.0
val_sample=1
val_sample_fraction=0.32
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=10
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/Revio.GM12878.244.ec.6_train.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/Revio.GM12878.244.ec.6_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/Revio.GM12878.244.ec.6_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/Revio.GM12878.244.ec.6_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_revio_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_revio_supervised_cnn.final.torch.pickle
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_revio_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_revio_semi_supervised_cnn.final.torch.pickle
save_pos=paper_v1/results/semi_train_revio_chemistry.npz
score_ap_json=paper_v1/results/semi_revio_score_precision.json
score_ap_table=paper_v1/results/semi_revio_score_precision.tsv

[train_revio_s3_3_2_chemistry]
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=0
train_sample_fraction=1.0
val_sample=1
val_sample_fraction=1.00
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=10
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/s3.bam.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/s4.bam_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/s3.bam.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/s4.bam_val.npz
best_supervised_model_name=paper_v1/models/m6A_revio_s3_3_2_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_revio_s3_3_2_supervised_cnn.final.torch.pickle
pretrain_model_name=paper_v1/models/m6A_3_2_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_revio_s3_3_2_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_revio_s3_3_2_semi_supervised_cnn.final.torch.pickle
save_pos=paper_v1/results/semi_train_revio_s3_3_2_chemistry.npz
score_ap_json=paper_v1/results/semi_revio_s3_3_2_score_precision.json
score_ap_table=paper_v1/results/semi_revio_s3_3_2_score_precision.tsv


[train_revio_s3_2_2_chemistry]
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=0
train_sample_fraction=1.0
val_sample=1
val_sample_fraction=1.00
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=10
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/s3.bam.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/s4.bam_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/s3.bam.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/s4.bam_val.npz
best_supervised_model_name=paper_v1/models/m6A_revio_s3_2_2_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_revio_s3_2_2_supervised_cnn.final.torch.pickle
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_revio_s3_2_2_semi_supervised_cnn.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_revio_s3_2_2_semi_supervised_cnn.final.torch.pickle
save_pos=paper_v1/results/semi_train_revio_s3_2_2_chemistry.npz
score_ap_json=paper_v1/results/semi_revio_s3_2_2_score_precision.json
score_ap_table=paper_v1/results/semi_revio_s3_2_2_score_precision.tsv