[train_2_2_chem_var1]
des=15bp+IPD+PW
sec_last_layer_size=25
last_layer_size=5
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=5
kernel_size_2=5
kernel_size_3=3
device=cuda
sup_lr=0.0001
input_size=6
input_length=15
input_window=7
sup_batch_size=32
sup_num_workers=8
supervised_train_epochs=30
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
sup_test_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn.final.torch
pr_fig=paper_v1/figures/sup_variant_prs.pdf
pr_fig_subset=paper_v1/figures/sup_variant_prs_subset.pdf

[train_2_2_chem_var2]
des=15bp+IPD
sec_last_layer_size=25
last_layer_size=5
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=5
kernel_size_2=5
kernel_size_3=3
device=cuda
sup_lr=0.0001
input_size=5
input_length=15
input_window=7
sup_batch_size=32
sup_num_workers=8
supervised_train_epochs=30
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
sup_test_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var2.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var2.final.torch
pr_fig=paper_v1/figures/sup_variant_prs.pdf
pr_fig_subset=paper_v1/figures/sup_variant_prs_subset.pdf

[train_2_2_chem_var3]
des=5bp+IPD+PW
sec_last_layer_size=5
last_layer_size=2
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=3
kernel_size_2=3
kernel_size_3=1
device=cuda
sup_lr=0.0001
input_size=6
input_length=5
input_window=2
sup_batch_size=32
sup_num_workers=8
supervised_train_epochs=30
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
sup_test_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var3.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var3.final.torch
pr_fig=paper_v1/figures/sup_variant_prs.pdf
pr_fig_subset=paper_v1/figures/sup_variant_prs_subset.pdf

[train_2_2_chem_var4]
des=5bp+IPD
sec_last_layer_size=5
last_layer_size=2
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=3
kernel_size_2=3
kernel_size_3=1
device=cuda
sup_lr=0.0001
input_size=5
input_length=5
input_window=2
sup_batch_size=32
sup_num_workers=8
supervised_train_epochs=30
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
sup_test_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var4.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var4.final.torch
pr_fig=paper_v1/figures/sup_variant_prs.pdf
pr_fig_subset=paper_v1/figures/sup_variant_prs_subset.pdf