[train_2_2_chem_var1]
des=15bp+IPD+PW
sec_last_layer_size=25
last_layer_size=5
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=5
kernel_size_2=5
kernel_size_3=3
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=15
input_window=7
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var1.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var1.final.torch
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var1.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var1.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var1.final.torch.pickle
save_pos=paper_v1/results/semi_train_2_2_chem_var1.npz
score_ap_json=paper_v1/results/semi_2_2_score_precision_var1.json
score_ap_table=paper_v1/results/semi_2_2_score_precision_var1.tsv

[train_2_2_chem_var2]
des=15bp+IPD
sec_last_layer_size=25
last_layer_size=5
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=5
kernel_size_2=5
kernel_size_3=3
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=5
input_length=15
input_window=7
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var2.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var2.final.torch
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var2.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var2.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var2.final.torch.pickle
save_pos=paper_v1/results/semi_train_2_2_chem_var2.npz
score_ap_json=paper_v1/results/semi_2_2_score_precision_var2.json
score_ap_table=paper_v1/results/semi_2_2_score_precision_var2.tsv

[train_2_2_chem_var3]
des=5bp+IPD+PW
sec_last_layer_size=5
last_layer_size=2
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=3
kernel_size_2=3
kernel_size_3=1
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=6
input_length=5
input_window=2
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var3.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var3.final.torch
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var3.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var3.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var3.final.torch.pickle
save_pos=paper_v1/results/semi_train_2_2_chemistry_var3.npz
score_ap_json=paper_v1/results/semi_2_2_score_precision_var3.json
score_ap_table=paper_v1/results/semi_2_2_score_precision_var3.tsv

[train_2_2_chem_var4]
des=5bp+IPD
sec_last_layer_size=5
last_layer_size=2
output_shape=2
out_channels_1=30
out_channels_2=10
out_channel_3=5
kernel_size_1=3
kernel_size_2=3
kernel_size_3=1
fdr=0.05
device=cuda
sup_lr=0.0001
semi_lr=0.0001
input_size=5
input_length=5
input_window=2
semi_batch_size=32
semi_num_workers=2
sup_batch_size=32
sup_num_workers=8
train_sample=1
train_sample_fraction=0.4
val_sample=1
val_sample_fraction=0.25
min_pos_proportion=0.0001
add_m6a_percent=1.0
total_m6a_percent=70.0
supervised_train_epochs=30
semi_supervised_train_epochs=20
sup_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2.npz
sup_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_val.npz
semi_train_data=paper_v1/data/fibertoolsMLTrain/PS00109_2_semi_train.npz
semi_val_data=paper_v1/data/fibertoolsMLTrain/PS00109_3_semi_val.npz
best_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var4.best.torch.pickle
final_supervised_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var4.final.torch
pretrain_model_name=paper_v1/models/m6A_2_2_supervised_cnn_var4.best.torch.pickle
best_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var4.best.torch.pickle
final_semi_supervised_model_name=paper_v1/models/m6A_2_2_semi_supervised_cnn_var4.final.torch.pickle
save_pos=paper_v1/results/semi_train_2_2_chem_var4.npz
score_ap_json=paper_v1/results/semi_2_2_score_precision_var4.json
score_ap_table=paper_v1/results/semi_2_2_score_precision_var4.tsv
